### ISSUE TITLE
Assertion failed in HuffmanTable::FillBits with certain images

### ISSUE THREAD

**Issue by mwilsnd** [veluca93/fpnge#23] opened 2022-12-20 03:10 UTC
I've discovered some images which fail the assert in [`HuffmanTable::FillBits`](https://github.com/veluca93/fpnge/blob/b43ae8ed968b06c9d08a01b8e77bdb26526388df/fpnge.cc#L313). I've been able to reproduce the issue on GCC and MSVC, samples loaded with lodepng or stb_image. Failure happens when trying to encode images in RGB format.

Sample images, including raw pixel data at 3 channel RGB:  [sample_images.zip](https://github.com/veluca93/fpnge/files/10264402/sample_images.zip)

Image 1:
- width: 256
- height: 256
- num_channels: 3
- bytes_per_channel: 1
- FPNGE_COMPRESS_LEVEL_BEST
- FPNGE_CICP_NONE
![img1](https://user-images.githubusercontent.com/53413200/208569746-634bcc68-29e9-43a6-9ac9-64b567fa61fd.png)

Image 2:
- width: 512
- height: 512
- num_channels: 3
- bytes_per_channel: 1
- FPNGE_COMPRESS_LEVEL_BEST/FPNGE_COMPRESS_LEVEL_DEFAULT/3/2/1 (failing _all_ compression levels, libpng encodes this image without issue)
- FPNGE_CICP_NONE
![sample0](https://user-images.githubusercontent.com/53413200/208571604-ffb8b0c4-50d2-469a-9886-82969b2f26f8.png)

**Comment by veluca93** [comment] 2022-12-20 16:16
I can't seem to reproduce the issue on either g++ or clang++, on Linux - are you running on Windows?

Are you able to reproduce the issue using fpnge_main.cc?

**Comment by mwilsnd** [comment] 2022-12-20 16:44
I'm not able to reproduce with fpnge_main.cc, no. Using Windows for this test. I looked at fpnge_main.cc in a debugger and it loads the PNG data to RGBA in memory which explains why. This issue only happens when running FPNGEEncode with num_channels set to 3, using RGB pixel data. You can either copy the output from lodepng and drop the alpha pixels or try with the raw pixel data in the sample zip.

**Comment by veluca93** [comment] 2022-12-20 16:57
Thank you for the bug report! Turns out I left some probably-debug code that is incorrect around. It should be fixed now...

**Closed** 2022-12-20 16:57 UTC
